# Generated by Django 4.2.23 on 2025-09-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен (ожидает сверки)'), ('reconciled', 'Скорректирован (закрыт)')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания к переучету')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный кладовщик')),
            ],
            options={
                'verbose_name': 'Переучет',
                'verbose_name_plural': 'Переучеты',
                'ordering': ['-created_at'],
                'permissions': [('can_reconcile_inventory', 'Может проводить сверку переучета')],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID объекта')),
                ('system_quantity', models.IntegerField(help_text='Количество в базе данных на момент добавления позиции', verbose_name='Кол-во по системе')),
                ('actual_quantity', models.IntegerField(default=0, help_text='Количество, введенное кладовщиком по факту', verbose_name='Фактическое кол-во')),
                ('reconciliation_status', models.CharField(choices=[('pending', 'Ожидает сверки'), ('reconciled', 'Сверено')], default='pending', max_length=20, verbose_name='Статус сверки')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventarization.inventorycount', verbose_name='Переучет')),
            ],
            options={
                'verbose_name': 'Позиция переучета',
                'verbose_name_plural': 'Позиции переучета',
                'unique_together': {('inventory_count', 'content_type', 'object_id')},
            },
        ),
    ]
