# Generated by Django 4.2.23 on 2025-09-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountitem',
            name='reconciliation_status',
            field=models.CharField(choices=[('pending', 'Ожидает сверки'), ('reconciled', 'Сверено')], default='pending', max_length=20, verbose_name='Статус сверки'),
        ),
    ]
