# Generated by Django 4.2.26 on 2026-02-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='status',
            field=models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Завершен (ожидает сверки)'), ('fixing', 'На пересчете'), ('reconciled', 'Скорректирован (закрыт)')], default='in_progress', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='inventorycountitem',
            name='reconciliation_status',
            field=models.CharField(choices=[('pending', 'Ожидает сверки'), ('reconciled', 'Сверено'), ('recount', 'Пересчитать')], default='pending', max_length=20, verbose_name='Статус сверки'),
        ),
    ]
