# Generated by Django 4.2.23 on 2025-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarization', '0002_inventorycountitem_reconciliation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycount',
            options={'ordering': ['-created_at'], 'permissions': [('can_reconcile_inventory', 'Может проводить сверку переучета')], 'verbose_name': 'Переучет', 'verbose_name_plural': 'Переучеты'},
        ),
    ]
