# Generated by Django 4.2.26 on 2026-02-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarization', '0002_alter_inventorycount_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountitem',
            name='manager_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий бухгалтера'),
        ),
    ]
