# Generated by Django 4.2.26 on 2026-01-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warehouse1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название материала')),
                ('article', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(default=warehouse1.models.generate_material_barcode, editable=False, max_length=15, unique=True, verbose_name='Штрихкод')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('min_quantity', models.IntegerField(default=0, verbose_name='Минимальное количество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='material/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'permissions': [('can_view_material_quantity', 'Может просматривать количество материалов на складе')],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория материала',
                'verbose_name_plural': 'Категории материалов',
            },
        ),
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет материала',
                'verbose_name_plural': 'Цвета материала',
            },
        ),
        migrations.CreateModel(
            name='OperationOutgoingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории выдачи')),
            ],
            options={
                'verbose_name': 'Категория выдачи',
                'verbose_name_plural': 'Категории выдачи',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Единица измерения')),
                ('short_name', models.CharField(max_length=10, verbose_name='Короткое обозначение')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='MaterialOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход'), ('adjustment', 'Корректировка:')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse1.material', verbose_name='Материал')),
                ('outgoing_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse1.operationoutgoingcategory', verbose_name='Назначение выдачи')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция с материалом',
                'verbose_name_plural': 'Операции с материалами',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse1.materialcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse1.materialcolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse1.unitofmeasure', verbose_name='Единица измерения'),
        ),
    ]
