# Generated by Django 4.2.26 on 2026-01-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название материала'),
        ),
    ]
