# Generated by Django 4.2.26 on 2026-02-22 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='color',
        ),
    ]
