# Generated by Django 4.2.23 on 2025-08-16 06:43

from django.db import migrations, models
import django.db.models.deletion
import warehouse1.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationOutgoingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории выдачи')),
            ],
            options={
                'verbose_name': 'Категория выдачи',
                'verbose_name_plural': 'Категории выдачи',
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='barcode',
            field=models.CharField(default=warehouse1.models.generate_unique_barcode, editable=False, max_length=12, unique=True, verbose_name='Штрихкод'),
        ),
        migrations.AddField(
            model_name='materialoperation',
            name='outgoing_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse1.operationoutgoingcategory', verbose_name='Назначение выдачи'),
        ),
    ]
