# Generated by Django 4.2.23 on 2025-09-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialoperation',
            name='operation_type',
            field=models.CharField(choices=[('incoming', 'Приход'), ('outgoing', 'Расход'), ('adjustment', 'Корректировка (+/-)')], max_length=20, verbose_name='Тип операции'),
        ),
    ]
