# Generated by Django 4.2.26 on 2026-02-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0002_remove_material_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaterialColor',
        ),
    ]
