# Generated by Django 4.2.23 on 2025-09-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0003_alter_materialoperation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальное количество'),
        ),
    ]
