# Generated by Django 4.2.23 on 2025-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse1', '0004_material_min_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('can_view_material_quantity', 'Может просматривать количество материалов на складе')], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
    ]
