# Generated by Django 4.2.23 on 2025-11-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(blank=True, max_length=255, verbose_name='Заказчик (Поставщик)')),
                ('due_date', models.DateField(verbose_name='Дата потребности (срок)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('planned', 'В плане'), ('partial', 'Частично выполнен'), ('completed', 'Выполнен')], default='pending', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
            ],
            options={
                'verbose_name': 'Заказ (Портфель)',
                'verbose_name_plural': 'Портфель заказов',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='Запрошено (кол-во)')),
                ('quantity_planned', models.PositiveIntegerField(default=0, verbose_name='Запланировано')),
                ('quantity_produced', models.PositiveIntegerField(default=0, verbose_name='Произведено (факт)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('planned', 'В плане'), ('partial', 'Частично выполнен'), ('completed', 'Выполнен')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказов',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_planned', models.PositiveIntegerField(verbose_name='План (на смену)')),
                ('quantity_produced', models.PositiveIntegerField(default=0, verbose_name='Факт (произведено)')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.productionorderitem', verbose_name='Из строки заказа')),
            ],
            options={
                'verbose_name': 'Задание на смену',
                'verbose_name_plural': 'Задания на смену (Доска)',
                'ordering': ['-created_at'],
            },
        ),
    ]
