# Generated by Django 4.2.23 on 2025-11-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse2', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция'),
        ),
        migrations.AddField(
            model_name='productionorderitem',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='todo.productionorder', verbose_name='Заказ'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderitem',
            unique_together={('production_order', 'product')},
        ),
    ]
