# Generated by Django 4.2.26 on 2025-12-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0001_initial'),
        ('todo', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['due_date'], 'verbose_name': 'Планирование заказов', 'verbose_name_plural': 'Планирование заказов'},
        ),
        migrations.AddField(
            model_name='productionorder',
            name='linked_shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='warehouse2.shipment', verbose_name='Связанная накладная'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('planned', 'В плане'), ('partial', 'Частично выполнен'), ('completed', 'Выполнен'), ('shipped', 'Передано в отгрузку')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='productionorderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('planned', 'В плане'), ('partial', 'Частично выполнен'), ('completed', 'Выполнен'), ('shipped', 'Передано в отгрузку')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
