# Generated by Django 4.2.26 on 2026-02-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse2', '0008_sender_stamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('printed', 'Первая печать (Фиксация)'), ('item_added', 'Добавлен товар после печати'), ('item_removed', 'Удален товар после печати'), ('item_updated', 'Изменено количество/цена после печати')], max_length=20)),
                ('details', models.TextField(verbose_name='Что именно изменилось')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='warehouse2.shipment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог аудита накладной',
                'verbose_name_plural': 'Логи аудита накладных',
                'ordering': ['-created_at'],
            },
        ),
    ]
