# Generated by Django 4.2.26 on 2026-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentauditlog',
            name='action',
            field=models.CharField(choices=[('item_added', 'Добавлен товар после печати'), ('item_removed', 'Удален товар после печати'), ('item_updated', 'Изменено количество/цена после печати')], max_length=20),
        ),
    ]
