# Generated by Django 4.2.26 on 2026-01-23 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouse2', '0006_product_external_image_url_alter_product_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название операции')),
                ('payment_type', models.CharField(choices=[('piece', 'Сдельная (за шт.)'), ('hourly', 'Почасовая (за час)')], default='piece', max_length=10)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ставка по умолчанию')),
            ],
            options={
                'verbose_name': 'Справочник операций',
                'verbose_name_plural': 'Справочник операций',
            },
        ),
        migrations.CreateModel(
            name='WorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Кол-во (шт/час)')),
                ('date_performed', models.DateField(verbose_name='Дата выполнения')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтверждено менеджером')),
                ('final_rate', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.operation', verbose_name='Операция')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse2.product', verbose_name='Изделие')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_entries', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_entries', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
        migrations.CreateModel(
            name='PenaltyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bonus', 'Премия'), ('penalty', 'Штраф')], max_length=10, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('reason', models.TextField(verbose_name='Причина/Комментарий')),
                ('date', models.DateField(auto_now_add=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
            options={
                'verbose_name': 'Премия/Штраф',
                'verbose_name_plural': 'Премии и штрафы',
            },
        ),
        migrations.CreateModel(
            name='TechCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена для этого товара')),
                ('operation', models.ForeignKey(limit_choices_to={'payment_type': 'piece'}, on_delete=django.db.models.deletion.CASCADE, to='payroll.operation', verbose_name='Операция')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_operations', to='warehouse2.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Техкарта: Операция товара',
                'verbose_name_plural': 'Техкарта: Операции товаров',
                'unique_together': {('product', 'operation')},
            },
        ),
    ]
