# Generated by Django 4.2.26 on 2026-01-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCardGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название техкарты (шаблона)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='TechCardOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в этой карте')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='payroll.techcardgroup')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.operation', verbose_name='Операция')),
            ],
            options={
                'unique_together': {('group', 'operation')},
            },
        ),
        migrations.DeleteModel(
            name='TechCard',
        ),
    ]
