# Generated by Django 4.2.26 on 2026-01-23 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payroll', '0002_techcardgroup_techcardoperation_delete_techcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Выплаченная сумма')),
                ('date_paid', models.DateField(auto_now_add=True, verbose_name='Дата выплаты')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий (напр. Аванс)')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
    ]
