# Generated by Django 4.2.23 on 2025-08-26 08:49

from django.db import migrations, models
import django.db.models.deletion
import warehouse2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукции')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(default=warehouse2.models.generate_product_barcode, editable=False, max_length=12, unique=True, verbose_name='Штрихкод продукции')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общее количество')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарезервировано')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет продукции',
                'verbose_name_plural': 'Цвета продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер продукции',
                'verbose_name_plural': 'Размеры продукции',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'В процессе сборки'), ('packaged', 'Собрано и упаковано'), ('assigned', 'Включено в накладную'), ('shipped', 'Отгружено')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отгрузка (накладная)',
                'verbose_name_plural': 'Отгрузки (накладные)',
            },
        ),
        migrations.CreateModel(
            name='ShipmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, verbose_name='Адрес/Получатель')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Сформирована'), ('shipped', 'Отправлена')], default='draft', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_produce', models.PositiveIntegerField(verbose_name='Количество к производству')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Производственный заказ',
                'verbose_name_plural': 'Производственные заказы',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse2.shipment', verbose_name='Отгрузка')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='warehouse2.shipmentdocument', verbose_name='Накладная'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productcolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productsize', verbose_name='Размер'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default=warehouse2.models.generate_package_barcode, editable=False, max_length=12, unique=True, verbose_name='Штрихкод упаковки')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse2.shipment', verbose_name='Привязан к отгрузке')),
            ],
            options={
                'verbose_name': 'Упаковка (баул)',
                'verbose_name_plural': 'Упаковки (баулы)',
            },
        ),
    ]
