# Generated by Django 4.2.23 on 2025-08-21 09:07
from django.db import migrations, models
import django.db.models.deletion
import uuid
from warehouse2.models import generate_unique_barcode_for_model, Product

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукции')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(default=lambda: generate_unique_barcode_for_model(Product), editable=False, max_length=50, unique=True, verbose_name='Штрихкод')),
                ('weight', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес (кг)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общее количество')),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Зарезервировано')),
            ],
            options={
                'verbose_name': 'Готовая продукция',
                'verbose_name_plural': 'Готовая продукция',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет продукции',
                'verbose_name_plural': 'Цвета продукции',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Размер продукции',
                'verbose_name_plural': 'Размеры продукции',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('packaged', 'Собрано'), ('shipped', 'Отгружено')], default='pending', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Отгрузка (накладная)',
                'verbose_name_plural': 'Отгрузки (накладные)',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_produce', models.PositiveIntegerField(verbose_name='Количество к производству')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Производственный заказ',
                'verbose_name_plural': 'Производственные заказы',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse2.shipment', verbose_name='Отгрузка')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productcolor', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productsize', verbose_name='Размер'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True, verbose_name='Штрихкод упаковки')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse2.shipment', verbose_name='Привязан к отгрузке')),
            ],
            options={
                'verbose_name': 'Упаковка (баул)',
                'verbose_name_plural': 'Упаковки (баулы)',
            },
        ),
    ]
