# Generated by Django 4.2.23 on 2025-10-10 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import warehouse2.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упаковки')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество товара в упаковке')),
                ('barcode', models.CharField(default=warehouse2.models.generate_package_barcode, editable=False, max_length=12, unique=True, verbose_name='Штрихкод упаковки')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукции')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='Артикул')),
                ('barcode', models.CharField(default=warehouse2.models.generate_product_barcode, max_length=12, unique=True, verbose_name='Штрихкод (штучный)')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу')),
                ('color', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('total_quantity', models.IntegerField(default=0, verbose_name='На балансе')),
                ('reserved_quantity', models.IntegerField(default=0, verbose_name='Зарезервировано')),
            ],
            options={
                'verbose_name': 'Штучный товар',
                'verbose_name_plural': 'Штучные товары',
                'permissions': [('can_view_product_quantity', 'Может просматривать количество продукции на складе'), ('can_edit_product_price', 'Может менять цену продукции на складе')],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория продукции',
                'verbose_name_plural': 'Категории продукции',
            },
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ФОП отправитель')),
            ],
            options={
                'verbose_name': 'ФОП отправитель',
                'verbose_name_plural': 'ФОП отправителя',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Адрес отгрузки')),
                ('recipient', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес отгрузки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('status', models.CharField(choices=[('pending', 'В процессе сборки'), ('packaged', 'Собрано'), ('shipped', 'Отгружено'), ('returned', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Кем создана')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_shipments', to=settings.AUTH_USER_MODEL, verbose_name='Кем собрана/отгружена')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse2.sender', verbose_name='ФОП отпраитель')),
            ],
            options={
                'verbose_name': 'Отгрузка',
                'verbose_name_plural': 'Отгрузки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_to_produce', models.PositiveIntegerField(verbose_name='Количество к производству')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Выполнен')], default='new', max_length=20, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Производственный заказ',
                'verbose_name_plural': 'Производственные заказы',
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (товаров или упаковок)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Фиксированная цена за ед.')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse2.package', verbose_name='Упаковка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse2.product', verbose_name='Штучный товар')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse2.shipment', verbose_name='Отгрузка')),
            ],
            options={
                'verbose_name': 'Позиция отгрузки',
                'verbose_name_plural': 'Позиции отгрузки',
            },
        ),
        migrations.CreateModel(
            name='ProductOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('incoming', 'Поступление (+)'), ('production', 'Производство (+)'), ('shipment', 'Отгрузка (-)'), ('adjustment', 'Корректировка (+/-)'), ('return', 'Возврат (+)')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='warehouse2.product', verbose_name='Продукция')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция с продукцией',
                'verbose_name_plural': 'Журнал операций с продукцией',
                'ordering': ['-timestamp'],
                'permissions': [('can_return_product', 'Может делать возврат накладных')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse2.productcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='package',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='warehouse2.product', verbose_name='Базовый продукт'),
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together={('product', 'quantity')},
        ),
    ]
