# Generated by Django 4.2.23 on 2025-09-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название упаковки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reserved_quantity',
            field=models.IntegerField(default=0, verbose_name='Зарезервировано'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.IntegerField(default=0, verbose_name='На балансе'),
        ),
    ]
