# Generated by Django 4.2.23 on 2025-10-03 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ФОП отправитель')),
            ],
            options={
                'verbose_name': 'ФОП отправитель',
                'verbose_name_plural': 'ФОП отправителя',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product_quantity', 'Может просматривать количество продукции на складе'), ('can_edit_product_price', 'Может менять цену продукции на складе')], 'verbose_name': 'Штучный товар', 'verbose_name_plural': 'Штучные товары'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse2.sender', verbose_name='ФОП отпраитель'),
        ),
    ]
