# Generated by Django 4.2.26 on 2026-01-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0002_product_is_archived_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='keycrm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='KeyCRM ID товара'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='keycrm_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='KeyCRM ID категории'),
        ),
    ]
