# Generated by Django 4.2.23 on 2025-09-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0002_alter_package_name_alter_product_reserved_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес отгрузки'),
        ),
    ]
