# Generated by Django 4.2.23 on 2025-09-06 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('warehouse2', '0003_shipment_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('production', 'Производство (+)'), ('shipment', 'Отгрузка (-)'), ('adjustment', 'Корректировка (+/-)'), ('return', 'Возврат (+)')], max_length=20, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('object_id', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время операции')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='warehouse2.product', verbose_name='Продукция')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Операция с продукцией',
                'verbose_name_plural': 'Журнал операций с продукцией',
                'ordering': ['-timestamp'],
            },
        ),
    ]
