# Generated by Django 4.2.26 on 2026-01-09 16:11

from django.db import migrations, models
import warehouse2.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0003_product_keycrm_id_productcategory_keycrm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(default=warehouse2.models.generate_product_barcode, max_length=15, unique=True, verbose_name='Штрихкод (штучный)'),
        ),
    ]
