# Generated by Django 4.2.23 on 2025-09-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0004_productoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='productoperation',
            name='operation_type',
            field=models.CharField(choices=[('incoming', 'Поступление (+)'), ('production', 'Производство (+)'), ('shipment', 'Отгрузка (-)'), ('adjustment', 'Корректировка (+/-)'), ('return', 'Возврат (+)')], max_length=20, verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'В процессе сборки'), ('packaged', 'Собрано'), ('shipped', 'Отгружено'), ('returned', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
