# Generated by Django 4.2.26 on 2026-01-09 18:19

from django.db import migrations, models
import warehouse2.models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0004_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='barcode',
            field=models.CharField(default=warehouse2.models.generate_package_barcode, editable=False, max_length=15, unique=True, verbose_name='Штрихкод упаковки'),
        ),
    ]
