# Generated by Django 4.2.23 on 2025-09-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0005_workorder_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_view_product_quantity', 'Может просматривать количество продукции на складе')], 'verbose_name': 'Штучный товар', 'verbose_name_plural': 'Штучные товары'},
        ),
        migrations.AlterModelOptions(
            name='productoperation',
            options={'ordering': ['-timestamp'], 'permissions': [('can_return_product', 'Может делать возврат накладных')], 'verbose_name': 'Операция с продукцией', 'verbose_name_plural': 'Журнал операций с продукцией'},
        ),
    ]
