# Generated by Django 4.2.26 on 2026-01-23 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_techcardgroup_techcardoperation_delete_techcard'),
        ('warehouse2', '0006_product_external_image_url_alter_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tech_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.techcardgroup'),
        ),
    ]
