# Generated by Django 4.2.26 on 2026-02-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse2', '0007_product_tech_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='stamp',
            field=models.ImageField(blank=True, help_text='Загрузите PNG с прозрачным фоном(400х400px)', null=True, upload_to='stamps/'),
        ),
    ]
